# Generated by Django 4.1.5 on 2023-01-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=1000)),
            ],
        ),
    ]
