# Generated by Django 4.0.8 on 2023-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('UserID', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='Content',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='table',
            name='Title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='User',
            field=models.CharField(default='', max_length=30),
        ),
    ]
