# Generated by Django 4.0.8 on 2023-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_alter_table_content_alter_table_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
