# Generated by Django 4.0.8 on 2023-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_email_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
