# Generated by Django 4.0.8 on 2023-02-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_email_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
    ]
