# Generated by Django 4.0.8 on 2023-02-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_downnvote_table_downvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='downvote',
            new_name='Downvote',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='upvote',
            new_name='Upvote',
        ),
    ]
