# Generated by Django 4.0.8 on 2023-03-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_downvote_table_downvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Downvote',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Upvote',
        ),
        migrations.AlterField(
            model_name='table',
            name='Content',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
