# Generated by Django 4.0.8 on 2023-03-05 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_vote_unique_together_vote_is_upvote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voted_on',
            new_name='vote_date',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_upvote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_before',
        ),
        migrations.AddField(
            model_name='table',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='Downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='Upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='blog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.table'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(default='upvote', max_length=8),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='User',
            field=models.CharField(max_length=250),
        ),
    ]
