# Generated by Django 4.0.8 on 2023-03-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_voted_on_vote_vote_date_remove_vote_is_upvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=8)),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.table')),
                ('voted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='app.user')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
