# Generated by Django 4.0.8 on 2023-03-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_votelog_voted_user_alter_votelog_voter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='votelog',
            name='voted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='app.user'),
        ),
        migrations.AlterField(
            model_name='votelog',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='app.user'),
        ),
    ]
