# Generated by Django 4.0.8 on 2023-03-06 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_user_alter_votelog_voted_user_alter_votelog_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
