# Generated by Django 4.0.8 on 2023-03-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_email_user_password_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
