# Generated by Django 4.0.8 on 2023-03-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_email_user_password_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votelog',
            name='voter',
        ),
    ]
