# Generated by Django 4.0.8 on 2023-03-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_votelog_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelog',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='app.user'),
            preserve_default=False,
        ),
    ]
