# Generated by Django 4.0.8 on 2023-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_votelog_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('blog_post', models.CharField(max_length=50)),
                ('vote_type', models.CharField(choices=[('U', 'Upvote'), ('D', 'Downvote')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='VoteLog',
        ),
    ]
