# Generated by Django 4.0.8 on 2023-03-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_vote_delete_votelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Downvote_count',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Upvote_count',
        ),
    ]
